[colors.primary]
background = "#000000"
foreground = "#95deff"

[font]
size = 10

[window]
decorations = "Full"
opacity = 0.8
unfocused_opacity = 0.4

[cursor.style]
blinking = "on"

[keyboard]
bindings = [{ key = "Return",   mods = "Super|Control", action = "SpawnNewInstance" }]