[colors.primary]
background = "#000000"
foreground = "#ffffff"

[font]
size = 10.0

[window]
decorations = "Full"
opacity = 0.5

[keyboard]
bindings = [{ key = "Return",   mods = "Super|Control", action = "SpawnNewInstance" }]