[colors.primary]
background = "#000000"
foreground = "#f7b9c6"

[font]
size = 10

[window]
decorations = "Full"
opacity = 0.75
unfocused_opacity = 0.25

[keyboard]
bindings = [{ key = "Return",   mods = "Super|Control", action = "SpawnNewInstance" }]